@extends('layouts.app')@section('title','Genres')@section('page_title','Genres')
@section('content')
<div class="d-flex justify-content-between mb-4"><p class="text-muted mb-0">Book genres and categories.</p><a href="{{ route('genres.create') }}" class="btn btn-primary rounded-pill">Add Genre</a></div>
<div class="card filter-card border-0 mb-4"><div class="card-body p-3"><form method="GET" class="row g-2"><div class="col-md-5"><input name="search" class="form-control" placeholder="Search name" value="{{ request('search') }}"></div><div class="col-md-3"><select name="status" class="form-select form-select-sm form-select-compact"><option value="">All</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div><div class="col-md-4 d-flex gap-2"><button class="btn btn-dark w-100">Filter</button>@if(request()->anyFilled(['search','status']))<a href="{{ route('genres.index') }}" class="btn btn-outline-secondary w-100">Clear</a>@endif</div></form></div></div>
<div class="card card-table border-0"><div class="table-responsive"><table class="table mb-0"><thead class="table-light"><tr><th>Name</th><th>Books</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($genres as $g)
<tr><td class="fw-bold">{{ $g->name }}</td><td>{{ $g->books_count }}</td><td><span class="badge {{ $g->status==='active'?'bg-success-subtle text-success':'bg-danger-subtle text-danger' }}">{{ ucfirst($g->status) }}</span></td>
<td class="text-end"><span class="table-actions"><a href="{{ route('genres.edit',$g) }}" class="btn btn-sm btn-outline-primary" title="Edit" aria-label="Edit"><i class="fa-solid fa-pen"></i></a> <button class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteModal" data-url="{{ route('genres.destroy',$g) }}" data-name="{{ $g->name }}"><i class="fa-solid fa-trash"></i></button></span></td></tr>
@empty<tr><td colspan="4" class="text-center py-4 text-muted">No genres found.</td></tr>@endforelse
</tbody></table></div><x-table-pagination :paginator="$genres" :sorts="['name'=>'Name','created_at'=>'Created']" /></div>
@endsection
